[package]
name = "gpu-info-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
crossterm = "0.28.1"
nix = { version = "0.29.0", features = ["user"] }
nvml-wrapper = "0.10.0"
prettytable-rs = "0.10.0"
procfs = "0.16.0"
